spring.application.name=web
spring.data.mongodb.uri=mongodb+srv://dbmgr:group5@bitesyncdb.dprb8p0.mongodb.net/?retryWrites=true&w=majority&appName=BiteSyncDB
spring.data.mongodb.database=biteSync
jwt.expiration=86400000
spring.main.allow-circular-references=true