spring.application.name=web
spring.data.mongodb.uri=mongodb+srv://dbmgr:<db_password>@bitesyncdb.dprb8p0.mongodb.net/?retryWrites=true&w=majority&appName=BiteSyncDB
spring.data.mongodb.database=biteSync
spring.main.allow-circular-references=true